# Generated by Django 4.1.3 on 2022-12-09 11:05

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('street_no', models.CharField(max_length=4)),
                ('postal_code', models.IntegerField(max_length=4)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('profile_photo', models.ImageField(upload_to='specialist/profile/')),
                ('physical', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=640)),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('NL', 'Dutch')], max_length=2)),
                ('speciality', models.CharField(choices=[('SPE', 'Speciality')], max_length=128)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='website.specialistaddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.parent')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.specialist')),
            ],
        ),
    ]
