# Generated by Django 4.1.3 on 2022-12-02 19:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('profile_photo', models.ImageField(upload_to='specialists/profiles/')),
                ('physical', models.BooleanField(default=True)),
                ('online', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=640)),
                ('language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('NL', 'Dutch')], max_length=2)),
                ('speciality', models.CharField(choices=[('SPE', 'Speciality')], max_length=128)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='website.specialistaddress')),
            ],
        ),
    ]
