# Generated by Django 4.1.3 on 2022-12-10 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('session_duration', models.DurationField()),
                ('morning_start', models.TimeField()),
                ('morning_end', models.TimeField()),
                ('afternoon_start', models.TimeField()),
                ('afternoon_end', models.TimeField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.specialist')),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
    ]
