# Generated by Django 4.1.3 on 2022-12-02 15:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistaddress',
            name='geo',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='specialistaddress',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
