# Generated by Django 4.1.3 on 2022-12-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.specialist')),
            ],
        ),
    ]
