# Generated by Django 4.1.3 on 2022-12-02 16:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_specialistaddress_geo_specialistaddress_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialistaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='specialistaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='specialistaddress',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='specialistaddress',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='specialistaddress',
            name='street',
        ),
        migrations.RemoveField(
            model_name='specialistaddress',
            name='street_no',
        ),
        migrations.AlterField(
            model_name='specialistaddress',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=[1, 1], srid=4326),
            preserve_default=False,
        ),
    ]
