# Generated by Django 4.1.3 on 2022-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistaddress',
            name='city',
            field=models.CharField(default='City', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistaddress',
            name='country',
            field=models.CharField(default='Country', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistaddress',
            name='postal_code',
            field=models.IntegerField(default=1000, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistaddress',
            name='street',
            field=models.CharField(default='Street', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialistaddress',
            name='street_no',
            field=models.CharField(default='10A', max_length=4),
            preserve_default=False,
        ),
    ]
